#+TITLE: Instalación de Alpine Linux
#+AUTHOR: Nieto Gallegos Isaac Julián
#+OPTIONS: toc:|2
#+PROPERTY: header-args :exports both
#+PROPERTY: header-args :eval no
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt, letterpaper]
#+LATEX_HEADER: \usepackage[margin=2.5cm]{geometry}      % Márgenes decentes
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{palatino}                   % Tipografía elegante
#+LATEX_HEADER: \usepackage{xcolor}                     % Colores personalizados
#+LATEX_HEADER: \usepackage{listings}

* Objetivos

Instalar la distribución de Linux elegida. En este caso, Alpine Linux.

* Montaje del sistema raíz

El mecanismo de instalación de Alpine Linux está constituido por dos scripts alternativa:

- setup-alpine, el cual puede ser aplicado sobre un disco duro entero y realizará la instalación automáticamente, según las especificaciones dadas por el usuario a través de variables de entorno y preguntas interactivas del mismo script.

- setup-disk, el cual es aplicado sobre un arbol de archivos ya montado en */mnt*. Sobre este sistema se detectan las particiones utilizadas y se realiza la instalación sobre estas mismas.

Para nuestro caso de uso, el segundo script será el usado. Por lo que lo primero que debemos de hacer es crear el arbol raíz en /mnt.

Montamos nuestra partición raíz sobre /mnt con:

#+begin_src bash 
mount -t ext4 <particion> /mnt
#+end_src

Luego, dentro de este, creamos la carpeta /boot con:

#+begin_src bash
mkdir -p /mnt/boot/efi
mount -t vfat <particion> /mnt/boot/efi
#+end_src

Y finalmente, cargamos la partición swap con:

#+begin_src bash 
swapon <particion>
#+end_src

Una vez hecho esto, tenemos preparado el arbol de archivos sobre el que se instalará el sistema operativo.

* Instalación de Alpine Linux

Instalamos los siguientes paquetes por si acaso:

#+begin_src bash
apk add grub-efi efibootmgr
#+end_src

Corremos el comando:

#+begin_src bash
BOOTLOADER=grub setup-disk -m sys /mnt
#+end_src

Al finalizar, reiniciamos y elegimos la nueva entrada en nuestro sistema UEFI. El resultado final es Alpine Linux instalado en bare-metal.

El tiempo de instalación final hasta el reinicio fue: *18:57 minutos*

* Sistema instalado

La versión de Alpine Linux instalada fue la más básica posible, con nada más que los paquetes por default, sin entorno gráfico ni ningún adicional.

El tiempo de arranque de esta instalación es de *26.79 segundos*, medidos desde el primer fotograma de la pantalla inicial de la UEFI. Si medimos el tiempo considerando solamente desde que el hardware le pasa el control a la partición de arranque del sistema, esto nos da *21.12 segundos*
